-- Generated from events.js by scripts/import-events.mjs
DELETE FROM events;
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-09-03', 'Japanese Tea Ceremony Beginners Course', 'University of West Florida Continuing Education', 'Pensacola, FL', 'This course blends hands-on tea ceremony lessons with engaging presentations on the history and philosophy behind the practice. Through guided tastings, interactive demonstrations, and thoughtful discussions, you''ll uncover the rituals, artistry, and cultural significance of this ancient tradition. Whether you''re seeking a meditative escape or fascinated by Japanese culture, this course invites you to slow down, savor the moment, and embrace the beauty of tea.No experience needed, just curiosity and an open mind.', 'https://registration.xendirect.com/uwf/coursedisplay.cfm?schID=1790&check=1');
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-08-22', 'BonFest Pensacola 2026', 'Japan-American Society of NWFL', 'Pensacola, FL', 'BonFest Pensacola is coming back! Save the date for Saturday, August 22, 12-4pm, at the Sanders Beach-Corinne Jones Resource Center. Watch this space for details. This will be a FREE event with traditional Obon music and dance, food and craft vendors, and more.', 'https://www.facebook.com/events/sanders-beach-corinne-jones-resource-center/bonfest-pensacola-2026/868908612955901/');
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-08-15', 'Morikami Summer Yukata Stroll', 'Morikami Museum & Japanese Gardens', 'Delray Beach, FL', 'An evening walk through the gardens in yukata, followed by a short tea demonstration. Casual and beginner-friendly — no kimono required to attend.', 'https://morikami.org');
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-10-25', '3rd Annual OKI Fest', 'Oki - Okinawa Kulture Impact', 'Fort Walton Beach, FL', 'Celebrate the Spirit of Okinawa Together! ✅ Free Admission & Entertainment!', 'https://facebook.com/events/s/3rd-annual-oki-fest/2020882632120354/');
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-08-16', 'Ikebana Chabana Japanese Flower Arrangement Class', 'Harry P. Leu Gardens', 'Orlando, FL', 'A specialized workshop focusing on Chabana, the traditional Japanese art of flower arrangement designed for the tea ceremony.', 'https://www.eventbrite.com/e/ikebana-chabana-japanese-flower-arrangement-class-tickets-1992285336071');
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-09-09', 'Ikebana International Naples Chapter Programs', 'Ikebana International Naples Chapter #160', 'Naples, FL', 'Ongoing 2026-2027 season of Ikebana demonstrations, workshops, and exhibitions at the Naples Botanical Garden.', 'https://www.ikebananaples.com/programs-and-events');
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-11-06', 'JAPAN Fes Florida — Miami', 'JAPAN Fes Florida', 'Miami, FL', 'A three-day Japan-focused festival in Miami with food vendors, performances, and cultural exhibits, part of a growing statewide JAPAN Fes series.', 'https://www.japanfes.com/florida/2026');
INSERT INTO events (date, title, host, location, description, link) VALUES ('2026-11-08', 'Orlando Japan Festival', 'Japan Association of Orlando', 'Kissimmee, FL', '2026年11月8日、キシミーの美しいレークフロントパークにて「日本祭」が開催されます。伝統的な太鼓の演奏や踊り、武道のデモンストレーション、そして美味しい日本食の屋台など、日本の魅力を存分に味わえる一日です。入場は無料ですので、ご家族やご友人と一緒に、秋の風を感じながら日本文化に触れてみませんか？

Join us for the annual Japan Festival at the scenic Kissimmee Lakefront Park! This event celebrates the rich heritage of Japan through captivating Taiko drumming, traditional dance, martial arts demos, and authentic cuisine. Admission is free, making it a perfect day out for families and friends to experience the spirit of Japan right here in Central Florida.', 'https://www.jorlando.org/orlando-japan-festival');
